{{- if .Values.ui.ingress.enabled -}}
{{- $fullName := include "datalab-ui.fullname" . -}}
{{ $servicePort := .Values.ui.service.http_port }}
{{ $host := .Values.ui.ingress.host }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ include "datalab-ui.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.ingress.tls }}
  tls:
  {{- range .Values.ui.ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  - host: mbod-gke-c2810-ssn.k8s-gcp.dlabanalytics.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: mbod-gke-c2810-ssn
          servicePort: 80
{{- end }}