spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: dlabdb
      port: 27017
      host: localhost
dlab:
  sbn: <CONF_SERVICE_BASE_NAME>
  bigQueryDataset: <DATASET_NAME>
  cron: 0 * * * * *

server:
  port: 8081
  servlet:
    contextPath: /api/billing

server.ssl.key-store-type: JKS
server.ssl.key-store: /Users/ofuks/keys/dlabcert/billing.jks
server.ssl.key-store-password: KEYSTORE_PASSWORD
server.ssl.key-alias: billing

logging:
  file: /var/opt/dlab/log/ssn/billing.log
  level:
    com:
      epam: trace