server:
  port: 8088
spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: <MONGO_PASSWORD>
      port: 27017
      host: localhost
dlab:
  sbn: <CONF_SERVICE_BASE_NAME>
  bigQueryDataset: <BILLING_DATASET_NAME>
  cron: 0 * * * * *

logging:
  file: /var/opt/dlab/log/ssn/billing.log
  level:
    com:
      epam: trace